[package]
name = "moo_sick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
reqwest = "0.11.23"
serenity = "0.12"
symphonia = "0.5.2"

[dependencies.songbird]
version = "0.4.0"
default-features = true

[dependencies.tokio]
version = "1.34.0"
features = ["macros", "signal", "rt-multi-thread"]
